language: python

services:
  - docker

os:
  - linux

python:
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install pytest pytest-cov
  - pip install -e .

script: pytest --cov=mk/ --cov-branch tests/

after_success:
- codecov
