language: python

dist: xenial

python:
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install pytest pytest-cov codecov
  - pip install -e .

script: pytest --cov=mk/ --cov-branch tests/

after_success:
  - codecov
